# Generated by Django 3.2.8 on 2022-01-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unique_code',
            field=models.CharField(default='qwer', max_length=128),
            preserve_default=False,
        ),
    ]
