# Generated by Django 3.2.8 on 2022-01-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_code',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
