# Generated by Django 3.2.8 on 2022-01-12 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_unique_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='unique_code',
        ),
    ]
