# Generated by Django 3.2.9 on 2021-11-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='disaster_level',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='point',
            name='disaster_type',
            field=models.CharField(choices=[('fire', 'fire'), ('water', 'water'), ('geo', 'geo'), ('meteo', 'meteo')], default='fire', max_length=80),
        ),
    ]
