# Generated by Django 3.2.9 on 2021-11-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20211119_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
