# Generated by Django 3.2.8 on 2022-03-03 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0002_point_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='point',
            name='verified',
        ),
        migrations.AddField(
            model_name='point',
            name='description',
            field=models.CharField(blank=True, max_length=360, verbose_name='Описание точки'),
        ),
        migrations.AddField(
            model_name='point',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Подтверждена ли точка уполномоченным лицом или организацией. Значение по умолчанию: не подтверждено', verbose_name='Подтверждена ли точка'),
        ),
        migrations.AddField(
            model_name='point',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='point',
            name='coordinates',
            field=models.CharField(max_length=80, verbose_name='Коордиаты точки'),
        ),
        migrations.AlterField(
            model_name='point',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='point',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_points', to=settings.AUTH_USER_MODEL, verbose_name='Автор точки'),
        ),
        migrations.AlterField(
            model_name='point',
            name='disaster_level',
            field=models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, max_length=1, verbose_name='Уровень опасности стихийного бедствия'),
        ),
        migrations.AlterField(
            model_name='point',
            name='disaster_type',
            field=models.CharField(choices=[('FIRE', 'Пожар'), ('WATER', 'Гидрологический характер'), ('GEO', 'Геологический характер'), ('METEO', 'Метеорологический характер')], default='UNKNOWN', max_length=80, verbose_name='Тип стихийного бедствия'),
        ),
        migrations.AlterField(
            model_name='point',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Наименование точки'),
        ),
    ]
