# Generated by Django 3.2.8 on 2022-03-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20220303_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='disaster_level',
            field=models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Уровень опасности стихийного бедствия'),
        ),
    ]
